random_seed: 42
min_method: L-BFGS-B
test_size: 0.2
val_size: 0.25
grid_search:
  min_samples_leaf_list:
  - 15
  - 25
  w_bound_list:
  - 10
  reg_lambda_list:
  - 0.1
  - 1
  - 10
  bin_penalty_alpha_list:
  - 0.01
  - 0.1
  - 0
  - 1
auto_bin:
  kmax: 5
  min_samples_leaf: 15
  smoothing: 0.01
  penalty_coef: 0.000405
single_config:
  bin_penalty_alpha: 1.0
  eps_counts: 1.0e-06
  bin_penalty_mode: shrinkage
monotonicity:
  enabled: true
  directions:
    PaFi: decreasing
    GCS: decreasing
    meanbp: free
    platelets: decreasing
    creatinine: increasing
    bilirubin: increasing
    norepinephrine: increasing
    epinephrine: increasing
    dopamine: increasing
    dobutamine: increasing
  recenter_weights: true
feature_names:
- PaFi
- GCS
- meanbp
- platelets
- creatinine
- bilirubin
- norepinephrine
- epinephrine
- dopamine
- dobutamine
target: mortality
stratify_col: mortality
optimization:
  integer_local_search: true
  integer_ls_max_passes: 15
  integer_ls_max_no_improve: 10
  integer_ls_step: 1
  enforce_positive_lr_coef: true
scaling:
  target_score_std: 10.0
  scale_penalty_coef: 5.0
  eps_std: 1.0e-12
